# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "enquete" ("enquete_id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"description" VARCHAR,"answer_key" VARCHAR NOT NULL,"admin_key" VARCHAR NOT NULL);
create table "question_option" ("enquete_id" INTEGER NOT NULL,"question_id" INTEGER NOT NULL,"question_option_id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"question_option_order" INTEGER NOT NULL,"description" VARCHAR NOT NULL);
create table "question" ("enquete_id" INTEGER NOT NULL,"question_id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"question_order" INTEGER NOT NULL,"description" VARCHAR NOT NULL,"answer_type" VARCHAR NOT NULL);
alter table "question_option" add constraint "fk_question_option_enquete" foreign key("enquete_id") references "enquete"("enquete_id") on update NO ACTION on delete NO ACTION;
alter table "question_option" add constraint "fk_question_option_question" foreign key("question_id") references "question"("question_id") on update NO ACTION on delete NO ACTION;
alter table "question" add constraint "fk_question_enquete" foreign key("enquete_id") references "enquete"("enquete_id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "question_option" drop constraint "fk_question_option_enquete";
alter table "question_option" drop constraint "fk_question_option_question";
alter table "question" drop constraint "fk_question_enquete";
drop table "enquete";
drop table "question_option";
drop table "question";

